language:
- node_js
- python
node_js:
- "0.12"
python:
- "2.7"
before_install:
- export PATH=$HOME/.local/bin:$PATH
- pip install --user `whoami` virtualenv
- virtualenv .env
- .env/bin/pip install kinto==1.3.1
env:
- KINTO_PSERVE_EXECUTABLE=.env/bin/pserve
after_script:
- npm run report-coverage
