language:
- node_js
- python
node_js:
- "0.12"
python:
- "2.7"
before_install:
- sudo apt-get install python-virtualenv
- virtualenv .env
- .env/bin/pip install kinto==1.3.1
- .env/bin/pserve test/kinto.ini &
